### ISSUE TITLE
Write Communications Guidelines Draft

### ISSUE THREAD

**Issue by bnord** [skypyproject/skypy#138] opened 2020-04-17 12:53 UTC
## Description

Communication guidelines will help us communicate fluidly and transparently. All participants knowing how we communicate is essential for trust pervading and persisting.

## Inputs
 - 

## Outputs
 - where we talk about different topics
 - how often we talk about topics

**Comment by rrjbca** [comment] 2020-04-23 14:45
Duplicate of #102; closing

**Closed by rrjbca** 2020-04-23 14:45 UTC
Labels: duplicate
