### ISSUE TITLE
Can we release SkyPy also on conda?

### ISSUE THREAD

**Issue by spxiwh** [skypyproject/skypy#100] opened 2020-04-15 10:20 UTC
The following page seems to give guidance for doing this?

https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html

Duncan Macleod is our local expert for this (Ian Harrison also knows him well) so would be a good point to ask if this doesn't go easily!

.... A future improvement to all of this would be tie this into Travis and have it all automated. We managed to set Travis up (in our "PyCBC" repository) so that when a new release is tagged it automatically gets uploaded to pypi, and then something does something and it ends up on conda as well.

**Comment by spxiwh** [comment] 2020-04-15 10:20
(I can't set tags or anything)

**Comment by andrew-lundgren** [comment] 2020-04-17 15:06
I gave this a quick try on sciserver, following the directions for `conda-build skeleton`. It failed with the first of many errors listed as

ERROR: Files/directories not found in /tmp/pip-wheel-bzdcm5cc/astropy-helpers/pip-egg-info

astropy-helpers is kind of strange because it's not supposed to be installed by users or developers directly; some sort of magic happens during the build process.

The next step is probably to try this on something where we have more control over the environment, maybe a Docker container or a machine where one of us is admin.

**Comment by a-r-williamson** [comment] 2020-07-16 13:56
I've made some progress here. Firstly, this was carried out on a RHEL 7 cluster that has pre-built conda environments I could use as the basis for a `skypy` one, which is what I did cloning `igwn-py37`. Then after trying with `conda-build skeleton pypi skypy` and hitting various errors, I came upon [`grayskull`](https://conda-forge.org/blog/posts/2020-03-05-grayskull/). This can be used to generate Conda recipes and it produced a different recipe from `conda-build skeleton` that I could build without hitting any errors.

```
conda create --name skypy-env --clone igwn-py37
conda activate skypy-env
conda install conda-build conda-verify grayskull
grayskull pypi skypy
conda-build skypy
```

**Comment by rrjbca** [comment] 2020-08-19 13:19
Thanks @a-r-williamson I've reproduced your `grayskull` recipe and opened a [pull request](https://github.com/conda-forge/staged-recipes/pull/12427) to add SkyPy to conda-forge

**Comment by a-r-williamson** [comment] 2020-08-19 13:34
Is there anything I can do a the moment to help?

**Comment by rrjbca** [comment] 2020-08-19 14:42
We are now on conda-forge: https://anaconda.org/conda-forge/skypy

Would be great if any conda users could test the installation: `conda install -c conda-forge skypy`

**Comment by rrjbca** [comment] 2020-08-19 14:44
Currently `conda install -c conda-forge skypy` does not work for me but `conda install -c cf-staging skypy` does

**Comment by rrjbca** [comment] 2020-08-19 15:39
`conda install -c conda-forge skypy` works for me now

**Comment by rrjbca** [comment] 2020-08-20 10:44
Seems to be working now so closing this. Any problems that arise open a issue.

**Closed by rrjbca** 2020-08-20 10:44 UTC
Labels: infrastructure, installation, release, v0.2 hack
